apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: signal-generation
resources:
  - namespace.yaml
  - configmap.yaml
  - timescaledb.yaml
  - redpanda.yaml
  - signal-api.yaml
  - cronjobs.yaml
